export const GET_GLOBAL_DATA="GET_GLOBAL_DATA";
export const GET_DAILY_DATA="GET_DAILY_DATA";
export const FETCH_ERROR="FETCH_ERROR";
export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_COUNTRY_DATA = "GET_COUNTRY_DATA";